version: '2'
services:
  proxy:
    build: proxy
    ports:
      - "80:80"
    depends_on:
      - lportal1
      - lportal2
  lportal1:
    build: lportal
  lportal2:
    build: lportal
  mysql:
    image: mdelapenya/mysql-utf8
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=lportal
      - character-set-server=utf8mb4
      - collation-server=utf8mb4_unicode_ci

